name: social_cv_client_dart_common
description: Shared code between AngularDart and Flutter Applications
version: 1.0.0

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  meta: 1.1.6
  equatable: ^0.1.6

  # Web Client
  http: ^0.12.0
  dio: ^2.1.3

  # Rx
  async: ^2.0.8
  rxdart: ^0.21.0

  # BLoC Pattern
  bloc: ^0.12.0

  # Serialization
  json_annotation: ^2.0.0

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

authors:
  - Axel LE BOT <axellebot@gmail.com>